# Generated by Django 5.2.1 on 2025-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_generationdata_iexmarketdata_loaddata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iexmarketdata',
            name='purchase_bids',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iexmarketdata',
            name='sell_bids',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
