# Generated by Django 3.2.25 on 2025-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_iexmarketdata_purchase_bids_iexmarketdata_sell_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscomDrawalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discom_name', models.CharField(max_length=100)),
                ('block_number', models.IntegerField()),
                ('schedule_date', models.DateField()),
                ('scheduled_drawal', models.FloatField()),
                ('actual_drawal', models.FloatField(blank=True, null=True)),
                ('revision_number', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GenerationDispatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_name', models.CharField(max_length=100)),
                ('block_number', models.IntegerField()),
                ('schedule_date', models.DateField()),
                ('scheduled_generation', models.FloatField()),
                ('actual_generation', models.FloatField(blank=True, null=True)),
                ('revision_number', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='iexmarketdata',
            index=models.Index(fields=['product'], name='data_app_ie_product_a91cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='iexmarketdata',
            index=models.Index(fields=['timestamp'], name='data_app_ie_timesta_580b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='generationdispatchschedule',
            index=models.Index(fields=['generator_name'], name='data_app_ge_generat_dd78fc_idx'),
        ),
        migrations.AddIndex(
            model_name='generationdispatchschedule',
            index=models.Index(fields=['schedule_date'], name='data_app_ge_schedul_2d9895_idx'),
        ),
        migrations.AddIndex(
            model_name='generationdispatchschedule',
            index=models.Index(fields=['timestamp'], name='data_app_ge_timesta_5f0b85_idx'),
        ),
        migrations.AddIndex(
            model_name='generationdispatchschedule',
            index=models.Index(fields=['revision_number'], name='data_app_ge_revisio_f10c57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generationdispatchschedule',
            unique_together={('generator_name', 'schedule_date', 'block_number', 'revision_number')},
        ),
        migrations.AddIndex(
            model_name='discomdrawalschedule',
            index=models.Index(fields=['discom_name'], name='data_app_di_discom__cf2e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='discomdrawalschedule',
            index=models.Index(fields=['schedule_date'], name='data_app_di_schedul_a38852_idx'),
        ),
        migrations.AddIndex(
            model_name='discomdrawalschedule',
            index=models.Index(fields=['timestamp'], name='data_app_di_timesta_d6faca_idx'),
        ),
        migrations.AddIndex(
            model_name='discomdrawalschedule',
            index=models.Index(fields=['revision_number'], name='data_app_di_revisio_2c417c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discomdrawalschedule',
            unique_together={('discom_name', 'schedule_date', 'block_number', 'revision_number')},
        ),
    ]
